#!/bin/bash

lst_ordis(){
  ldapsearch -x -h ldapmaster.enseeiht.fr -b ou=hosts,dc=n7,dc=fr puppetclass=$1 cn | grep n7\.fr | cut -f 2 -d ' ' | cut -f 1 -d '.'
}
tt_ordis(){
  for salle in c201 c202 c203 c204 c205 c206 c303 c304 c305 c306; do
    lst_ordis $salle
  done
}
valide(){
  ssh ${1}.e "matlab -r \"quit;\"" 1>/dev/null 2>/dev/null && echo $1 || echo "false"
}
liste="$(tt_ordis)"
number="5"
i=1
for Nens in 5 20 35 50 65; do
  j=1
  for percentInfo in 90 92 94 96 98; do
    while true; do
      first="$( echo "$liste" | sed -n 1p )"
      ordi="$( valide "$first" )"
      temp="$( echo "$liste" | sed -n "2~1p" )"
      liste="$temp"
      if [ "$ordi" != "false" ]; then
        echo "$ordi $number $i $j $Nens 0.$percentInfo "'ssh ${ordi}.e "cd Waves-simulation && matlab -r \"Classification_param($number, $i, $j, $Nens, 0.$percentInfo, true);quit;\"" &'
        ssh ${ordi}.e "cd Waves-simulation && matlab -r \"Classification_param($number, $i, $j, $Nens, 0.$percentInfo, true);quit;\"" 1>/dev/null &
        break
      fi
    done
    let 'j+=1'
  done
  let 'i+=1'
done
