#!/bin/bash

lst_ordis(){
  ldapsearch -x -h ldapmaster.enseeiht.fr -b ou=hosts,dc=n7,dc=fr puppetclass=$1 cn | grep n7\.fr | cut -f 2 -d ' ' | cut -f 1 -d '.'
}
tt_ordis(){
  for salle in c201 c202 c203 c204 c205 c206 c303 c304 c305 c306; do
    lst_ordis $salle
  done
}
valide(){
  ssh ${1}.e "which matlab" 2>/dev/null | grep "/usr/" 1>/dev/null && echo $1 || echo "false"
}
liste="$(tt_ordis)"
i=1
for p in 1 2 3 4 5 6 7 8 9; do
  j=1
  for m in 5 8 11 14 17 20 23 26 29; do
    while true; do
      first="$( echo "$liste" | sed -n 1p )"
      ordi="$( valide "$first" )"
      temp="$( echo "$liste" | sed -n "2~1p" )"
      if [ "$ordi" != "false" ]; then
        liste="$temp
$first"
        echo "ssh ${ordi}.e \"cd Waves-simulation/Sources_phase2 && export OMP_NUM_THREADS=4 && matlab -r \\\"Fortran_param(10, $i, $j, $p, $m);quit;\\\"\" 1>/dev/null &"
        ssh ${ordi}.e "cd Waves-simulation/Sources_phase2 && export OMP_NUM_THREADS=4 && matlab -r \"Fortran_param(10, $i, $j, $p, $m);quit;\"" 1>/dev/null &
        break
      else
        liste="$temp"
      fi
    done
    let 'j+=1'
  done
  let 'i+=1'
done
